branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
generate_mono_repository_global_tag = false
ignore_merge_commits = true
tag_prefix = "v"
skip_ci = "[skip ci]"
monorepo_version_separator = "/"

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "backend-api"
owner = "eShopOnMicroservices"
authors = [{ signature = "Ruslan Sorokin", username = "ruslanSorokin" }]

[bump_profiles]
