---
version: 3

includes:
  gen-proto-go:
    taskfile: taskfile/gen-proto-go.yaml
    internal: true

dotenv:
  - env/tool.env

tasks:
  lint:proto:
    cmds:
      - $BUF format --write
      - $BUF lint
      - $BUF breaking --against ".git#branch=main,recurse_submodules=true"

  gen:proto:
    deps: [lint:proto]
    cmd:
      task: gen-proto-go:generate
