---
version: 3

includes:
  gen-proto-go:
    taskfile: taskfile/gen-proto-go.yaml
    internal: true

tasks:
  lint:proto:
    sources:
      - src/proto
      - deps
    cmds:
      - buf format --write
      - buf lint
      - buf breaking --against ".git#branch=main,recurse_submodules=true"

  gen:proto:
    deps: [lint:proto]
    cmd:
      task: gen-proto-go:generate
